fix(PythonModifier): delete it
incompatible with IntelliJ IDEA Ultimate IU-241.13688.18 due to the following problems
Class not found (1 problem)
Access to unresolved class PyFunction.Modifier (1 problem)
Method PythonModifier.symbol(PyFunction) references an unresolved class PyFunction.Modifier. This can lead to NoSuchClassError exception at runtime.
Method not found (1 problem)
Invocation of unresolved method PyFunction.getModifier() (1 problem)
Method PythonModifier.symbol(PyFunction) contains an invokeinterface instruction referencing an unresolved method PyFunction.getModifier(). This can lead to NoSuchMethodError exception at runtime.